<html>
	<head>
		<link href="style.css" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="icon" href="Icona.ico">
	</head>
	<body>
		<ul>
			<li><a href="index.php"><img src="baseline_home_white_18dp.png"></a></li>
			<li><a href="elencolibriU.php">Libri</a></li>
			<li><a href="ricerca.php">Ricerca</a></li>
			<li><a href="inserimentoprestitoU.php">Richiedi prestito</a></li>
			<li><a href="statoprestiti.php">Stato prestiti</a></li>
      <li><a href="materiale.php">Materiale multimediale</a></li>
			<?php include "statoutenteA.inc" ?>
		</ul>
