<html>
	<head>
		<link href="style.css" rel="stylesheet" type="text/css">
		<link rel="icon" href="Icona.ico">
	</head>
	<body>
		<ul>
			<li><a href="index.php"><img src="baseline_home_white_18dp.png"></a></li>
			<li><a href="elencolibriU.php">Libri</a></li>
			<li><a href="ricerca.php">Ricerca</a></li>
			<li><a href="inserimentoprestitoU.php">Richiedi prestito</a></li>
			<li><a href="statoprestiti.php">Stato prestiti</a></li>
			<li><a href="materialeU.php">Materiale multimediale</a></li>
			<?php include "statoutenteA.inc" ?>
		</ul>
