<html>
    <head>
        <meta charset="windows-1252">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="style.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src='https://kit.fontawesome.com/a076d05399.js'></script>
		<style>
			body {
				width:80%;
				margin-left:10%;
				margin-right:10%;
				background: linear-gradient(to top right, #66ffff 0%, #66ff66 100%);
			}
	    .cella {
        border:1px black solid;
        padding: 5px;
      }
      table {
        border-collapse: collapse;
      }
      th {
        color:white;
        background-color: black;
      }
		  a {
			  text-decoration:none;
		  }
	</style>
    </head>
    <body>
	<div class="header">
        <h1><a href="index.php" style="color:#2A4B7C">Biblioteca digitale</a></h1>
	</div>
	</body>
</html>
